export const productsObjects = [
  { 
    code: "beb-coca",
    name: "Coca Cola",
    cost: 380,
    available: true,
    description: "Gaseosa Coca Cola",
    category: "bebidas",
    imagePath: "coke.png",
  },
  { 
    code: "beb-fanta",
    name: "Sprite",
    cost: 380,
    available: true,
    description: "Gaseosa Sprite",
    category: "bebidas",
    imagePath: "sprite.png",
  },
  { 
    code: "beb-sprite",
    name: "Fanta",
    cost: 380,
    available: false,
    description: "Gaseosa Fanta",
    category: "bebidas",
    imagePath: "fanta.png",
  },
  { 
    code: "emp-jyq",
    name: "Jamón y Queso",
    cost: 150,
    available: true,
    description: "Empanada de Jamón y Queso",
    category: "empanadas",
    imagePath: "empanada1.png",
  },
  { 
    code: "emp-salada",
    name: "Salada",
    cost: 150,
    available: true,
    description: "Empanada Salada",
    category: "empanadas",
    imagePath: "empanada2.png",
  },
  { 
    code: "emp-dulce",
    name: "Dulce",
    cost: 150,
    available: true,
    description: "Empanada Dulce",
    category: "empanadas",
    imagePath: "empanada3.png",
  },
  { 
    code: "emp-arabe",
    name: "Árabe",
    cost: 150,
    available: true,
    description: "Empanada Arabe",
    category: "empanadas",
    imagePath: "empanada4.png",
  },
  { 
    code: "ham-dribera",
    name: "Doble Ribera",
    cost: 1300,
    available: true,
    description: "Hamburguesa con doble medallón de carne, tosino, queso, tomate, lechuga y cebolla",
    category: "hamburguesas",
    imagePath: "hamburguesa1.png",
  },
  { 
    code: "ham-americana",
    name: "Americana",
    cost: 1100,
    available: false,
    description: "Hamburguesa con queso común, queso cheddar, tosino, pepinillos, tomate, lechuga y cebolla",
    category: "hamburguesas",
    imagePath: "hamburguesa2.png",
  },
  { 
    code: "ham-francesa",
    name: "Francesa",
    cost: 1200,
    available: true,
    description: "Hamburguesa con medallón de carne de 180 gramos, queso común, tosino, mayonesa casera, tomate, papas y cebolla morada",
    category: "hamburguesas",
    imagePath: "hamburguesa3.png",
  },
  { 
    code: "ham-comun",
    name: "Común",
    cost: 1000,
    available: true,
    description: "Hamburguesa con un medallon de carne, queso, pepinillos, cebolla, tomate y lechuga",
    category: "hamburguesa",
    imagePath: "hamburguesa4.png",
  },
  { 
    code: "ham-doble",
    name: "Doble",
    cost: 1300,
    available: true,
    description: "Hamburguesa con doble medallon de carne, queso, pepinillos, cebolla, tomate y lechuga",
    category: "hamburguesas",
    imagePath: "hamburguesa5.png",
  },
  { 
    code: "piz-champ",
    name: "Champiñones",
    cost: 1300,
    available: true,
    description: "Pizza de champiñones",
    category: "pizzas",
    imagePath: "pizza1.png",
  },
  { 
    code: "piz-pep",
    name: "Pepperoni",
    cost: 1300,
    available: true,
    description: "Pizza de pepperoni",
    category: "pizzas",
    imagePath: "pizza2.png",
  },
  { 
    code: "piz-napo",
    name: "Napolitana",
    cost: 1300,
    available: true,
    description: "Pizza napolitana",
    category: "pizzas",
    imagePath: "pizza3.png",
  },
]