export { Body } from './ModalBody'
export { Footer } from './ModalFooter'
export { Header } from './ModalHeader' 
export { Icon } from './ModalIcon'
export { Overlay } from './ModalOverlay'
export { Trigger } from './ModalTrigger' 
export { Modal } from './Modal'